### ISSUE TITLE
can't login anymore!

### ISSUE THREAD

**Issue by Unixware** [david63/privacypolicy#1]
Hi,

after installing the extension I am getting this message after any user logins:

`There are no registered paths for namespace "" in "policy_accept.html" at line 19.`

The users can't go anywhere. and there no way to access anymore the ACP !

Any fix? thanks!

**Comment by Sippan-66** [comment]
I can confirm this i get same results

There are no registered paths for namespace "" in "policy_accept.html" at line 19.

**Comment by Sippan-66** [comment]
Remove this in policy_accept.html  and clear cache manually so can u login again  
{% INCLUDEJS '@' ~ NAMESPACE ~ '/remove_url.js' %}

**Comment by Unixware** [comment]
Many thanks! This works!
