### ISSUE TITLE
I found a bug, how can I solve this problem?

### ISSUE THREAD

**Issue by AndroidMrRen** [david63/privacypolicy#2]
bug:
`SQL ERROR [ mysqli ]

Data too long for column 'privacy_lang_id' at row 1 [1406]

SQL

INSERT INTO phpbb_privacy_lang (privacy_lang_name, privacy_lang_description, privacy_lang_id, privacy_lang_text, privacy_text_bbcode_uid, privacy_text_bbcode_bitfield, privacy_text_bbcode_options) VALUES ('privacy_policy', 'Privacy policy', 'zh_cmn_hans', '<r><HR><s>[hr]</s><e>[/hr]</e></HR>\n<SIZE size=\"150\"><s>[size=150]</s><B><s>[b]</s>General Data Protection Regulation - 2018 (GDPR)<e>[/b]</e></B><e>[/size]</e></SIZE><br/>\n <br/>\nTo comply with the GDPR you need to be made aware that your %sitename% account will, at a bare minimum, contain a uniquely identifiable name (hereinafter “your user name”), a personal password used for logging into your account (hereinafter “your password”) and a personal, valid email address (hereinafter “your email”). Your information for your account at %sitename% is protected by data-protection laws applicable in the country that hosts us. Any information beyond your user name, your password, and your email address required by %sitename% during the registration process is either mandatory or optional, at the discretion of %sitename%. In all cases, you have the option of what information in your account is publicly displayed. Furthermore, within your account, you have the option to opt-in or opt-out of automatically generated emails.<br/>\n<br/>\nFurthermore we will store all of the IP address that you use to post with. Depending on your preferences %sitename% may send you emails to the email address that %sitename% holds in your account which will either be that you used when you registered or one that you have subsequently changed, but you are able to change these preferences from your User Control Panel (UCP) at any time should you wish to stop receiving them.<br/>\n<br/>\nThe personal details that you gave us when you signed up, or added later, will be used solely for the purposes of %sitename% board functionality. They will not be used for anything else and neither will they be passed on to any third party without your explicit consent. You can check, at any time, the personal details %sitename% is holding about you from the Profile section of your UCP.<br/>\n<br/>\nThe only other information about you is that which you decide to post in the fora, whereupon it is considered to be “publicly available” as it will have been indexed by search engines as well as on-line archive sites.</r>', '', '', 5)

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 994
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 196
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/david63/privacypolicy/controller/acp_edit_controller.php
LINE: 238
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/david63/privacypolicy/acp/privacypolicy_module.php
LINE: 35
CALL: david63\privacypolicy\controller\acp_edit_controller->edit()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: david63\privacypolicy\acp\privacypolicy_module->main()

FILE: [ROOT]/adm/index.php
LINE: 82
CALL: p_master->load_active()`
---------------------------------------------------
This is my configuration：
PHP：7.2.22
phpbb：3.2.8
MySQL：5.7.27

**Comment by david63** [comment]
Which version of Privacy Policy are you using?

The latest version cannot have this error with that field entry
